# Generated by Django 2.2 on 2022-03-01 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cook_time',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='prep_time',
        ),
        migrations.AddField(
            model_name='recipe',
            name='cook',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
