# Generated by Django 2.2 on 2022-03-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20220123_1715'),
        ('planner', '0002_auto_20220301_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='entry',
            field=models.ManyToManyField(related_name='recipes', to='login.User'),
        ),
    ]
