# Generated by Django 2.2 on 2022-03-03 19:44

from django.db import migrations, models
import planner.models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_recipe_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_date', models.DateField(null=True, verbose_name=planner.models.Recipe)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('fri', models.ForeignKey(null=True, on_delete=None, related_name='fri_menus', to='planner.Recipe')),
                ('mon', models.ForeignKey(null=True, on_delete=None, related_name='mon_menus', to='planner.Recipe')),
                ('sat', models.ForeignKey(null=True, on_delete=None, related_name='sat_menus', to='planner.Recipe')),
                ('sun', models.ForeignKey(null=True, on_delete=None, related_name='sun_menus', to='planner.Recipe')),
                ('thrus', models.ForeignKey(null=True, on_delete=None, related_name='thurs_menus', to='planner.Recipe')),
                ('tues', models.ForeignKey(null=True, on_delete=None, related_name='tues_menus', to='planner.Recipe')),
                ('wed', models.ForeignKey(null=True, on_delete=None, related_name='wed_menus', to='planner.Recipe')),
            ],
        ),
    ]
