# Generated by Django 2.2 on 2022-05-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20220123_1715'),
        ('planner', '0004_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='favorite',
            field=models.ManyToManyField(related_name='liked', to='login.User'),
        ),
    ]
