# Generated by Django 2.2 on 2022-05-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20220123_1715'),
        ('planner', '0005_recipe_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_created',
            field=models.ManyToManyField(related_name='menus', to='login.User'),
        ),
    ]
