# Generated by Django 2.2 on 2022-01-23 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
    ]
